name: Build and Deploy to Azure Web App - Neuroplanner

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: ☕ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: 🛠️ Build WAR with Maven
        run: mvn clean install

      - name: 📂 Toon target-map
        run: ls -lh target/

      - name: 📤 Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/ROOT.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 📥 Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: 🚀 Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'neuroplanner-bkg8e7ajgeemfpfz'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: java-app/ROOT.war
